### ISSUE TITLE
Does it support FLUTTER WEB or any future plans to support web?

### ISSUE THREAD

**Issue by KSingh1980** [pikaju/flutter-braintree#55] opened 2021-02-13 21:21 UTC
Does it support FLUTTER WEB or any future plans to support web?

**Comment by pikaju** [comment] 2021-07-29 13:17
I don't have any plans as of right now, but pull requests are always welcome. Duplicate of #21.

**Closed by pikaju** 2021-07-29 13:17 UTC

**Comment by Babwenbiber** [comment] 2022-03-06 13:33
For anyone still being interested in this...
I digged into the braintree docs and found some easy solution which works at least for creditcards.
1. create static file (e.g. in assets/html/index.html)
2. My content looks like this, but note that you can style it the way you want it:
```
<script src="https://js.braintreegateway.com/web/dropin/1.33.0/js/dropin.js"></script>

<div id="dropin-container"></div>
<button id="submit-button" class="button button--small button--green">Purchase</button>

<script type="text/javascript">
    var button = document.querySelector('#submit-button');

braintree.dropin.create({
  authorization: 'sandbox_g42y39zw_348pk9cgf3bgyw2b',
  selector: '#dropin-container'
}, function (err, instance) {
  button.addEventListener('click', function () {

    instance.requestPaymentMethod(function (err, payload) {
        //send data to flutter
        var content = JSON.stringify({'payload': payload, 'error': err})
        window.parent.postMessage(content, "*");
    });
  })
});
</script>
```

3.  Call this code from flutter and with the listener you can handle the none.
```
import 'dart:html' as html;
import 'dart:js' as js;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

const String viewID = "your-view-id";

class HtmlTryPage extends StatefulWidget {
  const HtmlTryPage({Key? key}) : super(key: key);

  @override
  State<HtmlTryPage> createState() => _HtmlTryPageState();
}

class _HtmlTryPageState extends State<HtmlTryPage> {
  @override
  void initState() {
    super.initState();
    html.window.addEventListener("message", (html.Event event) {
      var data = (event as html.MessageEvent).data;

      print(data);
    });
  }

  @override
  Widget build(BuildContext context) {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
        viewID,
        (int id) => html.IFrameElement()
          ..width = MediaQuery.of(context).size.width.toString()
          ..height = MediaQuery.of(context).size.height.toString()
          ..src = 'assets/html/ui.html'
          ..style.border = 'none');

    return const SizedBox(
      height: 500,
      child: HtmlElementView(
        viewType: viewID,
      ),
    );
  }
}

```
Hope this helps someone :)
