### ISSUE TITLE
Does it work with Flutter Web?

### ISSUE THREAD

**Issue by KSingh1980** [pikaju/flutter-braintree#52] opened 2021-01-04 19:52 UTC
Does it work with Flutter Web? Any plan to implement for the web.

**Comment by joe-getcouragenow** [comment] 2021-01-07 09:04
I was also curious

I suspect now as its using a ton of native OS stuff.

**Comment by dan1229** [comment] 2021-02-02 20:43
Also want updates on this - love this plugin and would really love a web version.

**Comment by KSingh1980** [comment] 2021-02-13 21:29
> Also want updates on this - love this plugin and would really love a web version.

A lot of people are moving to WEB from iOS/Android 30% cut in the payments. I would suggest, add support to WEB and it will be hugely popular.

**Comment by joe-getcouragenow** [comment] 2021-02-15 08:00
@KSingh1980 Yes this is what we need and partly why. But also because then you dont have the hassle of app store.

flutter web with "Add to Desktop" is quite a good compromise.

**Comment by KSingh1980** [comment] 2021-02-26 05:47
30% cut in all payments by Google and Apple is like DAYLIGHT ROBBERY.  Why would somebody use a mobile app for eCommerce? People are moving to PWA/Responsive web for all eCommerce apps.

**Comment by dan1229** [comment] 2021-03-09 02:54
If anyone's interested I've created a fork of this repo and reorganized it to build in the web version through the Braintree JS SDK.

I've setup the basic structure and am going to get to work on the actual functionality but if anyone thinks they can do it quickly or better please feel free to contribute or make a PR.

https://github.com/dan1229/flutter-braintree

**Comment by pikaju** [comment] 2021-07-29 13:18
Duplicate of #21. @dan1229 if its ready you can create a pull request to this repository if you like. Thanks!

**Closed by pikaju** 2021-07-29 13:18 UTC
